### ISSUE TITLE
API key does not start with "SG.".

### ISSUE THREAD

**Issue by kafarik** [lukeliasi/binance-dca-bot#23]
Hello dear developer team,
Please help me in resolving the following error:

npm run start
> binance-dca-bot@2.0.0 start /home/beisserikbay/binance-dca-bot
> node src/bot.js
API key does not start with "SG.".
/home/beisserikbay/binance-dca-bot/node_modules/mongodb-connection-string-url/lib/index.js:66
            throw new MongoParseError(`Invalid connection string "${uri}"`);
                  ^
MongoParseError: Invalid connection string "*your-mongodb-atlas-uri*"
    at new ConnectionString (/home/beisserikbay/binance-dca-bot/node_modules/mongodb-connection-string-url/lib/inde
x.js:66:19)
    at Object.parseOptions (/home/beisserikbay/binance-dca-bot/node_modules/mongodb/lib/connection_string.js:210:17
)
    at new MongoClient (/home/beisserikbay/binance-dca-bot/node_modules/mongodb/lib/mongo_client.js:62:46)
    at new MongoDb (file:///home/beisserikbay/binance-dca-bot/src/services/mongodb.js:14:17)
    at file:///home/beisserikbay/binance-dca-bot/src/bot.js:57:17
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-dca-bot@2.0.0 start: `node src/bot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-dca-bot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/beisserikbay/.npm/_logs/2021-12-16T21_58_30_042Z-debug.log

**Comment by informagico** [comment]
Hello @kafarik, just remove the `MONGODB_URI` variable from your configuration/environment.
It seems that you're still with the default `your-mongodb-atlas-uri` value.
Generally speaking, do not set any variable for a service that you're not gonna use.

Take a look at the [README](https://github.com/lukeliasi/binance-dca-bot#configure-the-bot) for further details.
Hope this will help you.
