### ISSUE TITLE
error: unexpected reserved word

### ISSUE THREAD

**Issue by KeyboardDabbler** [lukeliasi/binance-dca-bot#3]
I am getting a error when trying to run on windows.

```
C:\binance-dca-bot-main>npm run start

> binance-dca-bot@1.0.0 start C:\binance-dca-bot-main
> node ./src/index.js

(node:18324) ExperimentalWarning: The ESM module loader is experimental.
file:///C:/binance-dca-bot-main/src/index.js:59
await runBot();
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:88:18)
    at async link (internal/modules/esm/module_job.js:41:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-dca-bot@1.0.0 start: `node ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-dca-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\AppData\Roaming\npm-cache\_logs\2021-05-21T08_46_23_456Z-debug.log

C:\binance-dca-bot-main>
```

**Comment by lukeliasi** [comment]
What version of node are you using? Node 13+ is required to run the bot

**Comment by KeyboardDabbler** [comment]
my bad :p

this is now working, great job. Something simple, I like.

```
>node -v
v12.18.2
>node -v
v14.17.0
```
