### ISSUE TITLE
Getting the following error after npm run start

### ISSUE THREAD

**Issue by careonecomm** [lukeliasi/binance-dca-bot#7]
import { BinanceAPI } from "./services/binance-api.js";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-dca-bot@1.0.0 start: `node ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-dca-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by careonecomm** [comment]
Disregard, wrong node version, running now on v14
